zdbPool/urls.py
from django.urls import path

from . import views

app_name = 'zdbPool'
urlpatterns = [
	path('', views.index, name = 'index'),
	path('matchups/', views.matchups, name = 'matchups'),
	#ex: /matchups/selection
	path('matchups/selection/', views.selection, name='selection'),
	#ex: /gameresults/
	path('gameresults/', views.game_results, name='game_results'),
	#ex: /gameresults/1 display week 1 game results
	path('gameresults/<int:week>', views.weekly_game_results, name='weekly_game_results'),
	#ex: /scoreboard/ display total overall points
	path('scoreboard/', views.scoreboard, name='scoreboard'),
	#ex: /scoreboard/1 display week 1 points
	path('scoreboard/<int:week>', views.weekly_scoreboard, name='weekly_scoreboard'),
	#ex: /signup/
	path('signup/', views.signup, name='signup'),
]

zdbPoolSite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
	path('', include('zdbPool.urls')),
    path('admin/', admin.site.urls),
	path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += staticfiles_urlpatterns()

zdbPool/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

#NFL teams Model
class NFLTeam(models.Model):
	name = models.CharField(max_length = 50)
	city = models.CharField(max_length = 3)
	
	def __str__(self):
		return self.name

		
class Matchup(models.Model):
	HOME_TEAM_CHOICES = (('FAV_TEAM', 'Favorite'), ('UNDER_TEAM', 'Underdog'))
	
	favorite = models.ForeignKey(NFLTeam, related_name='fav', on_delete=models.CASCADE)
	underdog = models.ForeignKey(NFLTeam, related_name='under', on_delete= models.CASCADE)
	home_team = models.CharField(max_length= 15, choices = HOME_TEAM_CHOICES, default = 'FAV_TEAM')
	spread = models.FloatField()
	overUnder = models.FloatField()
	week = models.IntegerField()
	game_time = models.DateTimeField()
	
	def __str__(self):
		matchup = self.favorite.name + ' vs ' + self.underdog.name
		return matchup
		
		
class Pick(models.Model):
	WINNING_TEAM_CHOICES = (('FAV_TEAM', 'Favorite'), ('UNDER_TEAM', 'Underdog'))
	OVER_UNDER_CHOICES = (('OVER', 'Over'), ('UNDER', 'Under'))

	person = models.ForeignKey(User, on_delete = models.CASCADE)
	matchup = models.ForeignKey(Matchup, on_delete = models.CASCADE)
	winner = models.CharField(max_length  = 15, choices = WINNING_TEAM_CHOICES, default = 'FAV_TEAM')
	overUnder = models.CharField(max_length  = 15, choices = OVER_UNDER_CHOICES, default = 'OVER')
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)
	
	def __str__(self):
		pick_display = str(self.person) + ' ' + str(self.winner) + ' ' + str(self.overUnder) 
		return pick_display
		
	def week(self):
		return self.matchup.week
		
class GameResult(models.Model):
	
	matchup = models.ForeignKey(Matchup, on_delete=models.CASCADE)
	favorite_score = models.IntegerField()
	underdog_score = models.IntegerField()
	
	def __str__(self):
		result_display = str(self.matchup.favorite) + ' ' + str(self.favorite_score) + ' ' + str(self.matchup.underdog) + ' ' + str(self.underdog_score)
		return result_display

	def winner_against_spread(self):
		if self.favorite_score - self.matchup.spread > self.underdog_score:
			return 'FAV_TEAM'
		elif self.favorite_score - self.matchup.spread < self.underdog_score:
			return 'UNDER_TEAM'
		else:
			return none

	#winner_against_spread = property(get_winner_against_spread)

	def overUnderResult(self):
		totalScore = self.favorite_score + self.underdog_score
		if totalScore > self.matchup.overUnder:
			return 'OVER'
		elif totalScore < self.matchup.overUnder:
			return 'UNDER'
		else:
			return null

zdbPool/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
	first_name = forms.CharField(max_length=50, required=True, help_text='Required.', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter First Name'}))
	last_name = forms.CharField(max_length=50, required=True, help_text='Required.', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Last Name'}))
	email = forms.EmailField(max_length=254, help_text = 'Required. Supply a valid email', widget=forms.TextInput(attrs={'class': 'form-control', 'aria-describedby':'emailHelp', 'placeholder': 'Enter Email'}))
	password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Create Password'}))
	password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}))
	
	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')
		widgets = {
			'username': forms.TextInput(attrs = {'class': 'form-control', 'placeholder':'Create Username'})
		}
		

zdbPool/views.py
from datetime import datetime, timedelta
from django.utils import timezone

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.core.mail import send_mail

from .models import NFLTeam, Matchup, Pick, GameResult
from .forms import SignUpForm

def index(request):
	return render(request, 'zdbPool/index.html',)


@login_required	
def matchups(request):
	matchups = Matchup.objects.order_by('-week')
	dt = timezone.timedelta(days = 0) # simply used for debugging can remove when pushing out
	time_now = timezone.now() + dt
	if request.user.is_authenticated:
		user = request.user
	current_week = matchups[0].week
	person_picks = Pick.objects.filter(person = user)
	try:
		person_week_pick = person_picks.get(matchup__week = current_week)
		if time_now > person_week_pick.matchup.game_time:
			person_week_pick.started = True
	except (KeyError, Pick.DoesNotExist):
		person_week_pick = None
	matchups = Matchup.objects.filter(week = current_week)
	blank_out = blank_out_matchups(time_now)
	for matchup in matchups:
		if time_now > matchup.game_time:
			matchup.started = True
		else:
			matchup.started = False
	return render(request, 'zdbPool/matchups.html', {'matchups': matchups, 'person_week_pick':person_week_pick, 'blank_out':blank_out, })	

@login_required	
def selection(request):
	try:
		selected_matchup = Matchup.objects.get(pk = request.POST['matchup_id'])
	except (KeyError, Matchup.DoesNotExist):
		messages.add_message(request, messages.INFO, 'No change to selection')
		return HttpResponseRedirect(reverse('zdbPool:matchups'))
	else:
		person = request.user
		# delete after this week
		if request.POST["teamOptionsRadios"] == 'UNDER_TEAM':
			selected_winner = 'Giants'
		else:
			selected_winner = 'Cowboys'

		if request.POST['pick_id']:
			cur_pick = Pick.objects.get(pk = request.POST['pick_id'])
			created_at = cur_pick.created_at
			pick = Pick(pk = request.POST['pick_id'], person = person, 
				matchup = selected_matchup, created_at = created_at,
				winner = request.POST["teamOptionsRadios"], overUnder = request.POST['overUnderOptionsRadios'])
		else:
			pick = Pick(person = person, matchup = selected_matchup, 
				winner = request.POST["teamOptionsRadios"], overUnder = request.POST['overUnderOptionsRadios'])
		pick.save()
		# save a log of when each pick is made
		messages.add_message(request, messages.SUCCESS, 'You picked the {} '.format(pick.winner))
	
	return HttpResponseRedirect(reverse('zdbPool:index'))

@login_required
def game_results(request):
	
	game_results = GameResult.objects.order_by('-matchup__week')
	if len(game_results) == 0:
		messages.add_message(request, messages.INFO, 'No Game Results have been entered at this time')
		return HttpResponseRedirect(reverse('zdbPool:index'))
	else:
		current_week = game_results[0].matchup.week
		game_results = GameResult.objects.filter(matchup__week = current_week)
		weeks = list_weeks(current_week)
		return render(request, 'zdbPool/game_results.html', {'game_results' : game_results, 'weeks': weeks,})

@login_required	
def weekly_game_results(request, week):
	game_results = GameResult.objects.order_by('-matchup__week')
	current_week = game_results[0].matchup.week
	game_results = GameResult.objects.filter(matchup__week = week)
	weeks = list_weeks(current_week)
	return render(request, 'zdbPool/game_results.html', {'game_results' : game_results, 'weeks': weeks})
	
@login_required
def scoreboard (request):
	game_results = GameResult.objects.order_by('-matchup__week')
	if len(game_results) == 0:
		messages.add_message(request, messages.INFO, 'No Game Results have been entered at this time, so no scores are available')
		return HttpResponseRedirect(reverse('zdbPool:index'))
	else:
		current_week = game_results[0].matchup.week
		weeks = list_weeks(current_week)
		person_point_list = []
		persons = User.objects.all()
		for person in persons:
			total_points = 0
			picks = Pick.objects.filter(person = person)
			for pick in picks:
				if pick.matchup.week <= current_week:					
					week_points = getWeekpoints(pick)
					total_points = total_points + week_points
			temp_hold = [person, total_points]
			person_point_list.append(temp_hold)
		person_point_list.sort(key=lambda x: -x[1])
		return render(request, 'zdbPool/scoreboard.html', {'person_point_list': person_point_list, 'weeks': weeks,})
	
@login_required
def weekly_scoreboard (request, week):
	game_results = GameResult.objects.order_by('-matchup__week')
	current_week = game_results[0].matchup.week
	weeks = list_weeks(current_week)
	person_point_list = []
	persons = User.objects.all()
	for person in persons:
		picks = Pick.objects.filter(person = person)
		for pick in picks:
			if pick.matchup.week == week:
				week_points = getWeekpoints(pick)
				temp_hold = [person, week_points, week]
				person_point_list.append(temp_hold)
	person_point_list.sort(key=lambda x: -x[1])
	return render(request, 'zdbPool/scoreboard.html', {'person_point_list': person_point_list, 'weeks': weeks,})
	
def signup(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username = username, password = raw_password)
			login(request, user)
			return redirect('/')
	else:
		form = SignUpForm()
	return render(request, 'zdbPool/signup.html', {'form': form})

# function to return list of weeks up until current week	
def list_weeks(current_week):
	weeks = []
	while current_week > 0:
		weeks.append(current_week)
		current_week = current_week - 1
	list.sort(weeks)
	return weeks

#function to not return variable controlling whether to show the matchups or not	
def blank_out_matchups(time_now):
	blank_out_days = [0] #blankout day Monday
	
	if time_now.weekday() in blank_out_days:
		blank_out = True
	elif time_now.weekday() == 6 and time_now.hour >= 13 and time_now.minute > 00:
		blank_out = True
	else:
		blank_out = False
	return blank_out

# function to calculate the weekly points of a pick
def getWeekpoints(pick):
	points = 0
	try:
		game_result = GameResult.objects.get(matchup = pick.matchup)
	except (KeyError, Matchup.DoesNotExist):
		return points
	else:
		if pick.winner == game_result.winner_against_spread():
			points = points + 2
		if (pick.overUnder == game_result.overUnderResult()):
			points = points + 1
		return points
			

zdbPool/templates/zdbPool/game_results.html
{% extends 'layout.html' %}

{% block title %}Game Results{% endblock %}

{% block content %}
<h3> Week {{ game_results.0.matchup.week }} </h3>
<div class = "row">
	<h4 class = "col-sm-1">Week</h4>
	<ul class="pagination col-sm-11">
		{% for week in weeks %}
			{% if week == game_results.0.matchup.week %}
				<li class="page-item active">
					<a class="page-link" href="{% url 'zdbPool:weekly_game_results' week %}">{{week}}</a>
				</li>
			{% else %}
				<li class="page-item">
					<a class="page-link" href="{% url 'zdbPool:weekly_game_results' week %}">{{week}}</a>
				</li>
			{% endif %}
		{% endfor %}
	</ul>
</div>
<div class="table-responsive">
	<table class="table table-hover">
		<thead>
			<tr>
				<th scope="col"></th>
				<th scope="col">Favorite</th>
				<th scope="col">Score</th>
				<th scope="col">Underdog</th>
				<th scope="col">Score</th>
				<th scope="col">Points For Pick</th>
			</tr>
		</thead>
		<tbody>
			{% for game in game_results %}
				<tr class="table-active">
					<th scope="row"></th>
					<td>{{game.matchup.favorite.name}}</td>
					<td>{{game.favorite_score}}</td>
					<td>{{game.matchup.underdog.name}}</td>
					<td>{{game.underdog_score}}</td>
					<td>{{game.points_for_pick}}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
<script>
$('.table-active').on('click', function(event){
	const tablecollection = $('.table-active')
	alert("success")
	console.log(event)
	tablecollection.each(function(i){
		console.log($(this))
		if (this === event.currentTarget){
			$(this).children().css("background-color", "red")
		}

	})
});
</script>
{% endblock %}

zdbPool/templates/zdbPool/index.html
{% extends "layout.html" %}

{% block title %}DishDogz Pool{% endblock %}

{% block content %}
<div class="page-header">
	<h1 id="containers">The DishDogz Pool</h1>
</div>
<div class="jumbotron">
	<div class="display-3">
		<p class="lead">Welcome to The DishDogz Pool 2018</p>
	</div>
		{% if not user.is_authenticated %}
			<a class="btn btn-link" href="{% url 'login' %}">Log In</a>
		{% endif %}
</div>


{% endblock %}

zdbPool/templates/zdbPool/matchups.html
{% extends 'layout.html' %}

{% block title %}Game of the Weeek{% endblock %}

{% block content %}
<h3> Week {{ matchups.0.week }} </h3>
{% if person_week_pick %}
	<div class="alert alert-dismissible alert-warning">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<h4 class="alert-heading"> Current pick is {{ person_week_pick.winner}} and {{ person_week_pick.overUnder }}</h4>
	</div>
{% endif %}
	<form action="{% url 'zdbPool:selection' %}" method= "POST">
		<input type = "hidden" name ="pick_id" id ="pick_id" value ="{{person_week_pick.id}}"/>
		<input type = "hidden" name ="matchup_id" id ="matchup_id" value ="{{matchups.0.id}}"/>
		{% csrf_token %}
		<fieldset>
			<div class="row">
				<div class="col-lg-2"></div>
				<div class="col-lg-4">
					<fieldset class="form-group">
		      			<legend>Select Team</legend>
		     			 <div class="custom-control custom-radio">
		        			<input type="radio" class="custom-control-input" name="teamOptionsRadios" id="favoriteRadio" value="FAV_TEAM" checked="">
		          			<label class="custom-control-label" for="favoriteRadio">
		          				{{ matchups.0.favorite }} at -{{matchups.0.spread}}
		        			</label>
		      			</div>
		      			<div class="custom-control custom-radio">
		          			<input type="radio" class="custom-control-input" name="teamOptionsRadios" id="underdogRadio" value="UNDER_TEAM">
		          			<label class="custom-control-label" for="underdogRadio">
		          				{{ matchups.0.underdog }}
		        			</label>
		      			</div>
		      		</fieldset>
	      		</div>
	      		<div class="col-lg-4">
					<fieldset class="form-group">
		      			<legend>Select Over or Under</legend>
		     			 <div class="custom-control custom-radio">
		          			<input type="radio" class="custom-control-input" name="overUnderOptionsRadios" id="overRadio" value="OVER" checked="">
		          			<label class="custom-control-label" for="overRadio">
		          				Over {{matchups.0.overUnder}}
		        			</label>
		      			</div>
		      			<div class="custom-control custom-radio">
		          			<input type="radio" class="custom-control-input" name="overUnderOptionsRadios" id="underRadio" value="UNDER">
		          			<label class="custom-control-label" for="underRadio">
		          				Under {{matchups.0.overUnder}}
		        			</label>
		      			</div>
		      		</fieldset>
	      		</div>
	      	</div>
      		{% if person_week_pick %}
				<button type="submit" class="{% if person_week_pick.started or blank_out%}btn btn-primary disabled{% else %}btn btn-primary{% endif %}">Change Pick</button>
			{% elif person_week_pick == None %}
				<button type="submit" class="btn btn-primary">Submit Pick</button>
			{% endif %}
		</fieldset>
	</form>

{% endblock %}

zdbPool/templates/zdbPool/scoreboard.html
{% extends 'layout.html' %}

{% block title %}Scoreboard{% endblock %}

{% block content %}
<h2> Scoreboard </h2>
{% if person_point_list.0.2 %}
	<h4>Week {{person_point_list.0.2}}</h4>
{% else %}
	<h4>Overall Score</h4>
{% endif %}
<div class = "row">
	<h4 class = "col-sm-1">Week</h4>
	<ul class="pagination col-sm-11">
		{% for week in weeks %}
			{% if week == person_point_list.0.2 %}
				<li class="page-item active">
					<a class="page-link" href="{% url 'zdbPool:weekly_scoreboard' week %}">{{week}}</a>
				</li>
			{% else %}
				<li class="page-item">
					<a class="page-link" href="{% url 'zdbPool:weekly_scoreboard' week %}">{{week}}</a>
				</li>
			{% endif %}
		{% endfor %}
		<li class="{% if person_point_list.0.2 %}page-item{% else %}page-item active{% endif %}">
			<a class="page-link" href="{% url 'zdbPool:scoreboard' %}">Overall</a>
		</li>
	</ul>
	
</div>
<div class="table-responsive">
	<table class="table table-hover">
		<thead>
			<tr>
				<th scope="col">Ranking</th>
				<th scope="col">Player</th>
				<th scope="col">Score</th>

			</tr>
		</thead>
		<tbody>
			{% for item in person_point_list %}
				<tr class="table-active">
					<th scope="row">{{forloop.counter}}</td>
					<td>{{item.0}}</td>
					<td>{{item.1}}</td>

				</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% endblock %}

zdbPool/templates/zdbPool/signup.html
{% extends "layout.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<h2>Sign Up</h2>
<form method = "post">
	<fieldset>
		<div class="col-sm-5">
			{% csrf_token %}
			{% include 'zdbPool/signup_form.html' %}
			<button class="btn btn-primary" type="submit"> Sign Up</button>
		</div>
	</fieldset>
</form>
{% endblock %}

zdbPool/templates/zdbPool/signup_form.html
{% for field in form %}
	<div class = "form-group">
		<label>{{field.label_tag}}</label>
		{{field}}
		<div>{{ field.errors }}</div>
		{% if field.errors %}
			<div>{{ field.help_text }}</div>
		{% endif %}
	</div>
{% endfor %}